version: '3.8'

services:
  jenkins:
    build:
      context: .
      dockerfile: Dockerfile.jenkins

    container_name: jenkins

    privileged: true
    user: root

    environment:
      - JAVA_OPTS=-Xmx3072m -Xms512m -XX:+UseG1GC

    mem_limit: 4096m

    ports:
      - "8080:8080"
      - "50000:50000"

    volumes:
      - ~/jenkins_compose/jenkins_configuration:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock

#docker-compose -f .\jenkins-compose.yaml up