services:
  postgres:
    image: postgres:16
    container_name: homework29_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: homework29
    ports:
      - "5432:5432"

  app:
    build: .
    container_name: homework29_app
    depends_on:
      - postgres
    environment:
      DATABASE_URL: postgresql://postgres:1234@postgres:5432/homework29
    volumes:
      - ./allure-results:/app/allure-results
